sistematico1 = int(input("ingrese la primer nota del primer sistematico (max: 30): "))
sistematico2 = int(input("ingrese la nota del segundo sistematico (max : 30): "))
sistematico3 = int(input("ingrese la nota del tercer sistematico (max : 40) : "))
nota = (sistematico1 + sistematico2 + sistematico3)
print("la nota del estudiante es: ", nota)